### ISSUE TITLE
__main__ error message

### ISSUE THREAD

**Issue by whottel** [sanger-pathogens/ariba#187]
Hi,

I recently installed ariba on Red Hat linux using pip. It installs without error, however when I run the command "python ariba test out" in the directory where ariba is installed I get the error " can't find '__main__' module in 'ariba' ". Any ideas on why I would be getting this error?

**Comment by martinghunt** [comment]
Ariba is written in python 3, so prefixing the command with `python` will make python 2 try to run it, and hence the error saying it can't find the packages, because they are installed for python 3.

Try running `/your/install/path/ariba` from anywhere. If pip3 installed ariba then that should work. No need to prefix the command with anything.

**Comment by whottel** [comment]
I re-installed using pip3. However the command **~/.local/lib/python3.5/site-packages/ariba**  returns "-bash: /Users/hottel/.local/lib/python3.5/site-packages/ariba is a directory". 

Adding the prefix **python3** to the above command returns the main module error as before.

**Comment by whottel** [comment]
I believe I have solved this issue by activating a Bioconda environment and running **conda install ariba --user**. The ariba command now appears to be working as expected.
Thanks for your help!
