### ISSUE TITLE
The meaning of the flag "ref_seq_choose_fail"

### ISSUE THREAD

**Issue by IEkAdN** [sanger-pathogens/ariba#199]
Hello,

[The document about the command `flag`](https://github.com/sanger-pathogens/ariba/wiki/Task:-flag) describes the flag `ref_seq_choose_fail` as `this is set to true if something went wrong when trying to find the closest reference sequence within a cluster`. Could you please tell me what does `something went wrong` means?  Does this indicate the case when `the closest reference sequence does not belong to the cluster`, which is described in the ARIBA paper?

**Comment by martinghunt** [comment]
It could happen for many reasons, including when the closest ref seq does not belong to the cluster. In that case, you should see 'Closest reference is XYZ and does not belong to cluster' in the log. Otherwise something else happened, eg there were no matches between the assembly and the reference for whatever reason (like a bad assembly with short contigs).

**Comment by IEkAdN** [comment]
Thank you for your quick response and detailed explanation.
