### ISSUE TITLE
Use ariba run for several isolates in batch

### ISSUE THREAD

**Issue by BaMagalhaes** [sanger-pathogens/ariba#262]
I would like to check resistance in my isolate collection (74 isolates) by performing ariba run on all isolates at the same time. However, I would like to have a report.tsv for each isolate individually, in order to create a presence/absence table.

I have tried two ways:
1- Concatenation of the forward and reverse reads in two files. However, I only get one report of the pooled resistance of all isolates;
2- The following command:
$ docker run --rm -it -v /home/ubuntu/data:/data sangerpathogens/ariba ariba run --verbose /data/out.card.prepareref /data/*_R1.fastq.gz /data/*_R2.fastq.gz /data/out_individual_st1076.run
But it doesn't detect the reads, which are on /home/ubuntu/data:/data.

Do you have any suggestion?

**Comment by kpepper** [comment]
Hi **@BaMagalhaes**,
1. Use a bash "for" loop to call _ariba run_ via the docker command, for each of your isolate files, specifying a different output directory for each run (e.g. use a counter to append to the output directory name) - so that you end up with one output directory & report per isolate. You could also do this easily if you have access to a compute farm, via bsub.
2. How do you mean it doesn't detect the reads - do you get an error reported? Your files are in the /home/ubuntu/data folder?

**Comment by kpepper** [comment]
Closing this issue, as it's now several months old.
